In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/onkardasari2609/the-complete-works-of-william-shakespeare/pg100.txt


In [2]:
file = open("/kaggle/input/datasets/onkardasari2609/the-complete-works-of-william-shakespeare/pg100.txt",'r')
text = file.read()

In [3]:
print('total characters:', len(text))

total characters: 5378663


In [4]:
import tensorflow
from tensorflow.keras.preprocessing.text import Tokenizer

In [5]:
tokenizer = Tokenizer()

In [6]:
tokenizer.fit_on_texts([text])

In [7]:
len(tokenizer.word_index)

30049

In [8]:
lines = text.splitlines()

In [9]:
sentences = []

for line in lines:
    line = line.strip()

    if line:
        sentences.append(line)

In [10]:
print(sentences[0])
print(sentences[1])
print(sentences[2])

The Project Gutenberg eBook of The Complete Works of William Shakespeare
This ebook is for the use of anyone anywhere in the United States and
most other parts of the world at no cost and with almost no restrictions


In [11]:
sequences = []

for sentence in sentences:
    sequence = tokenizer.texts_to_sequences([sentence])[0]
    sequences.append(sequence)

sequences[0]

[17460, 1105, 2450, 4901, 5, 1, 3245, 1509, 5, 1168, 6108]

In [12]:
input_sequences = []

for sequence in sequences:
    for i in range(1,len(sequence)):
        input_sequences.append(sequence[:i+1])

In [13]:
input_sequences

[[17460, 1105],
 [17460, 1105, 2450],
 [17460, 1105, 2450, 4901],
 [17460, 1105, 2450, 4901, 5],
 [17460, 1105, 2450, 4901, 5, 1],
 [17460, 1105, 2450, 4901, 5, 1, 3245],
 [17460, 1105, 2450, 4901, 5, 1, 3245, 1509],
 [17460, 1105, 2450, 4901, 5, 1, 3245, 1509, 5],
 [17460, 1105, 2450, 4901, 5, 1, 3245, 1509, 5, 1168],
 [17460, 1105, 2450, 4901, 5, 1, 3245, 1509, 5, 1168, 6108],
 [19, 4901],
 [19, 4901, 11],
 [19, 4901, 11, 16],
 [19, 4901, 11, 16, 1],
 [19, 4901, 11, 16, 1, 308],
 [19, 4901, 11, 16, 1, 308, 5],
 [19, 4901, 11, 16, 1, 308, 5, 4490],
 [19, 4901, 11, 16, 1, 308, 5, 4490, 6109],
 [19, 4901, 11, 16, 1, 308, 5, 4490, 6109, 9],
 [19, 4901, 11, 16, 1, 308, 5, 4490, 6109, 9, 1],
 [19, 4901, 11, 16, 1, 308, 5, 4490, 6109, 9, 1, 3564],
 [19, 4901, 11, 16, 1, 308, 5, 4490, 6109, 9, 1, 3564, 2559],
 [19, 4901, 11, 16, 1, 308, 5, 4490, 6109, 9, 1, 3564, 2559, 2],
 [107, 159],
 [107, 159, 889],
 [107, 159, 889, 5],
 [107, 159, 889, 5, 1],
 [107, 159, 889, 5, 1, 176],
 [107, 159, 889

In [14]:
max_len = max([len(x) for x in input_sequences])

In [15]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequences = pad_sequences(input_sequences, maxlen = max_len, padding = 'pre')

In [16]:
padded_input_sequences

array([[    0,     0,     0, ...,     0, 17460,  1105],
       [    0,     0,     0, ..., 17460,  1105,  2450],
       [    0,     0,     0, ...,  1105,  2450,  4901],
       ...,
       [    0,     0,     0, ...,     4,   130,   267],
       [    0,     0,     0, ...,   130,   267,   379],
       [    0,     0,     0, ...,   267,   379,  7701]], dtype=int32)

In [17]:
X = padded_input_sequences[:,:-1]

In [18]:
X

array([[    0,     0,     0, ...,     0,     0, 17460],
       [    0,     0,     0, ...,     0, 17460,  1105],
       [    0,     0,     0, ..., 17460,  1105,  2450],
       ...,
       [    0,     0,     0, ..., 30049,     4,   130],
       [    0,     0,     0, ...,     4,   130,   267],
       [    0,     0,     0, ...,   130,   267,   379]], dtype=int32)

In [19]:
y = padded_input_sequences[:,-1]

In [20]:
y

array([1105, 2450, 4901, ...,  267,  379, 7701], dtype=int32)

## We acheived our dataset

In [21]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y,num_classes = 30050)

In [22]:
y.shape

(818643, 30050)

In [23]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [24]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input,Embedding,LSTM,Dense

In [25]:
model = Sequential()

model.add(Input(shape=(56,)))
model.add(Embedding(30050, 100))
model.add(LSTM(150))
model.add(Dense(30050, activation='softmax'))

model.compile(
    loss='sparse_categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

model.summary()

I0000 00:00:1787228477.338780      58 gpu_device.cc:2020] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 13756 MB memory:  -> device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5
I0000 00:00:1787228477.341852      58 gpu_device.cc:2020] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 13756 MB memory:  -> device: 1, name: Tesla T4, pci bus id: 0000:00:05.0, compute capability: 7.5


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 56, 100)        │     3,005,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 150)            │       150,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 30050)          │     4,537,550 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 7,693,150 (29.35 MB)

 Trainable params: 7,693,150 (29.35 MB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.fit(X,y,epochs = 10)